# Generated by Django 3.1.8 on 2021-05-31 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='nombre_genero',
            fields=[
                ('genero_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='peliculas.genero')),
            ],
            bases=('peliculas.genero',),
        ),
    ]
