# Generated by Django 3.1.8 on 2021-06-02 19:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0003_auto_20210602_1241'),
    ]

    operations = [
        migrations.AddField(
            model_name='pelicula',
            name='link',
            field=models.URLField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
