# Generated by Django 3.1.8 on 2021-06-03 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0004_pelicula_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='fecha',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('año', models.DateField(max_length=55)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'fecha',
                'verbose_name_plural': 'fechas',
            },
        ),
        migrations.RemoveField(
            model_name='pelicula',
            name='fecha',
        ),
        migrations.AddField(
            model_name='pelicula',
            name='fecha',
            field=models.ManyToManyField(to='peliculas.fecha'),
        ),
    ]
