# Generated by Django 3.1.8 on 2021-06-03 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0005_auto_20210603_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fecha',
            name='año',
            field=models.CharField(max_length=55),
        ),
    ]
